
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gabriel
 */
public class Formulario extends javax.swing.JFrame {
    public ArrayList<String> ArrayLista = new ArrayList();
    public String texto ="";
    public int numero;
    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BComum = new javax.swing.JButton();
        BRapido = new javax.swing.JButton();
        BPrioritario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TSenhaGerada = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        BCaixa1 = new javax.swing.JButton();
        BCaixa2 = new javax.swing.JButton();
        BCaixa3 = new javax.swing.JButton();
        BCaixa4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        TSenhaParaAtendimento = new javax.swing.JLabel();
        TCaixaParaAtendimento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Para Clientes:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        BComum.setText("Comum");
        BComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BComumActionPerformed(evt);
            }
        });

        BRapido.setText("Rápido");
        BRapido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRapidoActionPerformed(evt);
            }
        });

        BPrioritario.setText("Prioritário");
        BPrioritario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPrioritarioActionPerformed(evt);
            }
        });

        jLabel1.setText("Escolha seu tipo de atendimento");

        jLabel2.setText("Sua senha é:");

        TSenhaGerada.setEditable(false);
        TSenhaGerada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TSenhaGerada.setText("Senha Gerada");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BComum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BRapido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BPrioritario))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TSenhaGerada, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(BRapido)
                    .addComponent(BComum)
                    .addComponent(BPrioritario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TSenhaGerada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Para caixas:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        BCaixa1.setText("Caixa 1");
        BCaixa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCaixa1ActionPerformed(evt);
            }
        });

        BCaixa2.setText("Caixa 2");
        BCaixa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCaixa2ActionPerformed(evt);
            }
        });

        BCaixa3.setText("Caixa 3");
        BCaixa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCaixa3ActionPerformed(evt);
            }
        });

        BCaixa4.setText("Caixa 4");
        BCaixa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCaixa4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BCaixa1)
                    .addComponent(BCaixa3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BCaixa2)
                    .addComponent(BCaixa4))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BCaixa1)
                    .addComponent(BCaixa2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BCaixa3)
                    .addComponent(BCaixa4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Painel de atendimento:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        TSenhaParaAtendimento.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        TSenhaParaAtendimento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TSenhaParaAtendimento.setText("Senha");

        TCaixaParaAtendimento.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TCaixaParaAtendimento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TCaixaParaAtendimento.setText("Caixa");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TCaixaParaAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TSenhaParaAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TSenhaParaAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TCaixaParaAtendimento)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCaixa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCaixa1ActionPerformed
        // TODO add your handling code here:        
        int ContemP = 0;
        int Contem = 0;
        texto = "";
        String procurar;
        
        for(int i = 0; i <= numero; i++){
            procurar = "P-";
            procurar += i;
            
         if((ArrayLista.contains(procurar) == true) && ContemP==0){
            ContemP = 1;
            ArrayLista.remove(procurar);
            //numero--;
            texto = procurar;
            TSenhaParaAtendimento.setText(texto);
         } 
        }
        
        if (ContemP==0){
        for(int i = 0; i <= numero; i++){
            procurar = "C-";
            procurar += i;
            if((ArrayLista.contains(procurar) == true) && Contem==0){
            Contem = 1;
            ArrayLista.remove(procurar);
            //numero--;
            texto = procurar;
            TSenhaParaAtendimento.setText(texto);
         }
            procurar = "R-";
            procurar += i;
            if((ArrayLista.contains(procurar) == true) && Contem==0){
            Contem = 1;
            ArrayLista.remove(procurar);
            //numero--;
            texto = procurar;
            TSenhaParaAtendimento.setText(texto);
         }
    } 
}    
        TCaixaParaAtendimento.setText("Caixa 1");
        Contem = 0;
        ContemP = 0;  
    }//GEN-LAST:event_BCaixa1ActionPerformed

    private void BComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BComumActionPerformed
        Senha objSenha = new Senha();
        texto = "";
        texto += "C-";
        numero++;
        texto += numero;
        ArrayLista.add(texto);
        TSenhaGerada.setText(texto);
        objSenha.setArrayFila(ArrayLista);
    }//GEN-LAST:event_BComumActionPerformed

    private void BRapidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRapidoActionPerformed
        // TODO add your handling code here:
        Senha objSenha = new Senha();
        texto = "";
        texto += "R-";
        numero++;
        texto += numero;
        ArrayLista.add(texto);
        TSenhaGerada.setText(texto);
        objSenha.setArrayFila(ArrayLista);
        
    }//GEN-LAST:event_BRapidoActionPerformed

    private void BPrioritarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPrioritarioActionPerformed
        // TODO add your handling code here:
        Senha objSenha = new Senha();
        
        texto = "";
        texto += "P-";
        numero++;
        texto += numero;
        ArrayLista.add(texto);
        TSenhaGerada.setText(texto);
        objSenha.setArrayFila(ArrayLista);
    }//GEN-LAST:event_BPrioritarioActionPerformed

    private void BCaixa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCaixa2ActionPerformed
        // TODO add your handling code here:
        int ContemR = 0;
        int Contem = 0;
        texto = "";
        String procurar;
        
        for(int i = 0; i <= numero; i++){
            procurar = "R-";
            procurar += i;
            
         if((ArrayLista.contains(procurar) == true) && ContemR==0){
            ContemR = 1;
            ArrayLista.remove(procurar);
            //numero--;
            texto = procurar;
            TSenhaParaAtendimento.setText(texto);
         } 
        }
        
        if (ContemR==0){
        for(int i = 0; i <= numero; i++){
            procurar = "C-";
            procurar += i;
            if((ArrayLista.contains(procurar) == true) && Contem==0){
            Contem = 1;
            ArrayLista.remove(procurar);
            //numero--;
            texto = procurar;
            TSenhaParaAtendimento.setText(texto);
         }
            procurar = "P-";
            procurar += i;
            if((ArrayLista.contains(procurar) == true) && Contem==0){
            Contem = 1;
            ArrayLista.remove(procurar);
            //numero--;
            texto = procurar;
            TSenhaParaAtendimento.setText(texto);
         }
    } 
}    
        TCaixaParaAtendimento.setText("Caixa 2");
        Contem = 0;
        ContemR = 0;
        
    }//GEN-LAST:event_BCaixa2ActionPerformed

    private void BCaixa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCaixa3ActionPerformed
        // TODO add your handling code here:
        int ContemR = 0;
        int Contem = 0;
        texto = "";
        String procurar;
        
        for(int i = 0; i <= numero; i++){
            procurar = "R-";
            procurar += i;
            
         if((ArrayLista.contains(procurar) == true) && ContemR==0){
            ContemR = 1;
            ArrayLista.remove(procurar);
            //numero--;
            texto = procurar;
            TSenhaParaAtendimento.setText(texto);
         } 
        }
        
        if (ContemR==0){
        for(int i = 0; i <= numero; i++){
            procurar = "C-";
            procurar += i;
            if((ArrayLista.contains(procurar) == true) && Contem==0){
            Contem = 1;
            ArrayLista.remove(procurar);
            //numero--;
            texto = procurar;
            TSenhaParaAtendimento.setText(texto);
         }
            procurar = "P-";
            procurar += i;
            if((ArrayLista.contains(procurar) == true) && Contem==0){
            Contem = 1;
            ArrayLista.remove(procurar);
            //numero--;
            texto = procurar;
            TSenhaParaAtendimento.setText(texto);
         }
    } 
}    
        TCaixaParaAtendimento.setText("Caixa 3");
        Contem = 0;
        ContemR = 0;
     
    }//GEN-LAST:event_BCaixa3ActionPerformed

    private void BCaixa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCaixa4ActionPerformed
        // TODO add your handling code here:
        int ContemC = 0;
        int Contem = 0;
        texto = "";
        String procurar;
        
        for(int i = 0; i <= numero; i++){
            procurar = "C-";
            procurar += i;
            
         if((ArrayLista.contains(procurar) == true) && ContemC==0){
            ContemC = 1;
            ArrayLista.remove(procurar);
            //numero--;
            texto = procurar;
            TSenhaParaAtendimento.setText(texto);
         } 
        }
        
        if (ContemC==0){
        for(int i = 0; i <= numero; i++){
            procurar = "R-";
            procurar += i;
            if((ArrayLista.contains(procurar) == true) && Contem==0){
            Contem = 1;
            ArrayLista.remove(procurar);
            //numero--;
            texto = procurar;
            TSenhaParaAtendimento.setText(texto);
         }
            procurar = "P-";
            procurar += i;
            if((ArrayLista.contains(procurar) == true) && Contem==0){
            Contem = 1;
            ArrayLista.remove(procurar);
            //numero--;
            texto = procurar;
            TSenhaParaAtendimento.setText(texto);
         }
    } 
}    
        TCaixaParaAtendimento.setText("Caixa 4");
        Contem = 0;
        ContemC = 0;
    
    }//GEN-LAST:event_BCaixa4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Formulario().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCaixa1;
    private javax.swing.JButton BCaixa2;
    private javax.swing.JButton BCaixa3;
    private javax.swing.JButton BCaixa4;
    private javax.swing.JButton BComum;
    private javax.swing.JButton BPrioritario;
    private javax.swing.JButton BRapido;
    private javax.swing.JLabel TCaixaParaAtendimento;
    private javax.swing.JTextField TSenhaGerada;
    private javax.swing.JLabel TSenhaParaAtendimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
